version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.26.0
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./lib/zeebe-hazelcast-exporter-0.10.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-0.10.0.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.20.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  checkout-service:
    container_name: checkout-service
    image: node:12
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./checkout:/app
      - ./checkout/node_modules:/app/node_modules
    networks:
      - zeebe_network
    command: npm run start:dev
  order-service:
    container_name: order-service
    image: node:12
    working_dir: /app
    volumes:
      - ./order:/app
      - ./order/node_modules:/app/node_modules
    networks:
      - zeebe_network
    command: npm run start:dev
  payment-service:
    container_name: payment-service
    image: node:12
    working_dir: /app
    volumes:
      - ./payment:/app
      - ./payment/node_modules:/app/node_modules
    networks:
      - zeebe_network
    command: npm run start:dev
  inventory-service:
    container_name: inventory-service
    image: node:12
    working_dir: /app
    volumes:
      - ./inventory:/app
      - ./inventory/node_modules:/app/node_modules
    networks:
      - zeebe_network
    command: npm run start:dev
